// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `SelectHealthPing`. */
export interface ISelectHealthPingResult {
    ok: number | null;
}

export interface Queries {
    SelectHealthPing: ISelectHealthPingResult;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
}

export {};
